#!/usr/bin/env bash
#
# Fleet audit: does any public document contradict the org register?
#
#   org-drift-audit.sh [--check] [--list]
#
# WHY
#
# Writing a fact down in many places is what failed. The org story has been
# restated across READMEs, CLAUDE.md files, and marketing copy — each time
# with slight variations — and those variations became contradictions. One
# repo says "incorporation pending", another says the legal name, a third
# describes a host that isn't the actual host. The fix is a small
# machine-readable register for facts that have no other producer, and a
# check that fails when a public document contradicts it.
#
# WHAT IS FORBIDDEN
#
# Per registers/org.json, these claims are contradictions:
#   - "incorporation pending" (legalStatus is unregistered)
#   - "bitbaum AG" (legalStatus is unregistered)
#   - "AI-first product studio" or "AI product studio" as what bitbaum is
#   - github.io/bitbaum as a host (host is Hetzner)
#   - the legal personal name Georgy Butaev on public docs
#   - a live door named in a README that disagrees with apps.conf
#
# CENTRAL, NOT A COPY PER REPO — the rule this repo already lives by. The
# register is SSOT; agents read it. They do not restate the org story. A
# new claim is a register row or it does not ship.
#
# DEFAULT SCAN: GitHub API via `gh`, not local checkouts. A ratchet that sees
# nothing prevents nothing. Scans public docs (README.md, CLAUDE.md, AGENTS.md,
# docs/*.md, site/*.md, marketing/*.md, *.html) from the bitbaum org's default
# branches. Set USE_LOCAL=1 to scan DEV_ROOT instead (for testing).
#
# THE BASELINE IS A RATCHET
#
# Existing violations are counted and baselined. The point is a new lie
# cannot land. The inventory is GENERATED by this script. Counts may FALL or
# hold; they may never RISE without that decision being visible in the same
# PR that adds the violation.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REGISTER="${REGISTER:-$HERE/../../registers/org.json}"
BASELINE="${BASELINE:-$HERE/org-drift.baseline}"
INVENTORY="${INVENTORY:-$HERE/org-drift-inventory.txt}"
ORG="${ORG:-bitbaum}"
USE_LOCAL="${USE_LOCAL:-0}"

# ---------------------------------------------------------------- pure helpers

# forbidden_patterns — regex alternatives for claims that contradict the register
forbidden_patterns() {
  cat <<'EOF'
incorporation[- ]pending
bitbaum AG\b
AI-first product studio
AI product studio
github\.io/bitbaum
Georgy Butaev
EOF
}

# is_public_doc <path> — only public-facing documentation and marketing
is_public_doc() {
  case "$1" in
    *README.md|*CLAUDE.md|*AGENTS.md) return 0 ;;
    *docs/*.md|*site/*.md|*content/*.md|*marketing/*.md) return 0 ;;
    *.html) return 0 ;;
    *) return 1 ;;
  esac
}

# is_exempt_path <path> — paths whose job is to describe history
is_exempt_path() {
  case "$1" in
    docs/archive/*|*/docs/archive/*) return 0 ;;
    *org-drift-audit.sh|*org-drift.baseline|*org-drift-inventory.txt) return 0 ;;
    *test-org-drift-audit.sh) return 0 ;;
    *registers/org.json) return 0 ;;
    *SHARED.md|*STACK.md) return 0 ;;
    */.git/*|*/node_modules/*|*/dist/*|*/.next/*) return 0 ;;
    *) return 1 ;;
  esac
}

# baseline_keys <file> — `repo/path` per line, comments and blanks dropped
baseline_keys() {
  [ -f "$1" ] || return 0
  sed -e 's/#.*//' -e 's/[[:space:]]*$//' -e '/^[[:space:]]*$/d' "$1"
}

# in_baseline <key> <keys...>
in_baseline() {
  local key="$1"; shift
  local k
  for k in "$@"; do [ "$k" = "$key" ] && return 0; done
  return 1
}

# gh_list_repos — list repos in the org
gh_list_repos() {
  gh repo list "$ORG" --limit 1000 --json name --jq '.[].name' 2>/dev/null || {
    echo "gh repo list failed" >&2
    return 1
  }
}

# gh_default_branch <repo> — get default branch name
gh_default_branch() {
  gh api "repos/$ORG/$1" --jq '.default_branch' 2>/dev/null || echo "main"
}

# gh_check_file <repo> <path> <branch> — fetch and check one file
gh_check_file() {
  local repo="$1" path="$2" branch="$3"
  gh api "repos/$ORG/$repo/contents/$path?ref=$branch" --jq '.content' 2>/dev/null | base64 -d 2>/dev/null || true
}

# repo_ref <dir> — audit the shared default branch, not a local feature branch
repo_ref() {
  git -C "$1" rev-parse --verify -q origin/main   >/dev/null 2>&1 && { printf 'origin/main';   return; }
  git -C "$1" rev-parse --verify -q origin/master >/dev/null 2>&1 && { printf 'origin/master'; return; }
  printf 'HEAD'
}

# fetch_apps_conf — retrieve the current apps.conf from fleetcrown
fetch_apps_conf() {
  if ! command -v gh >/dev/null 2>&1; then
    echo "# apps.conf unavailable: gh not found" >&2
    return 1
  fi
  gh api repos/bitbaum/fleetcrown/contents/scripts/hetzner/apps.conf --jq '.content' 2>/dev/null | base64 -d 2>/dev/null || {
    echo "# apps.conf unavailable: fetch failed" >&2
    return 1
  }
}

# parse_apps_conf_doors <apps_conf_content> — extract domain→repo mappings
parse_apps_conf_doors() {
  awk -F'|' '
    /^#/ || /^[[:space:]]*$/ { next }
    NF >= 3 {
      domains = $3
      repo = $4
      gsub(/^\/home\/g\/dev\//, "", repo)
      n = split(domains, domainlist, ",")
      for (i = 1; i <= n; i++) {
        if (domainlist[i] != "-" && domainlist[i] != "") {
          print domainlist[i] "|" repo
        }
      }
    }
  '
}

if [ -n "${ORG_DRIFT_AUDIT_LIB_ONLY:-}" ]; then return 0; fi

# ---------------------------------------------------------------------- sweep

MODE=check
case "${1:-}" in
  --check|"") MODE=check ;;
  --list)     MODE=list ;;
  *) echo "unknown flag: $1" >&2; exit 2 ;;
esac

mapfile -t KEYS < <(baseline_keys "$BASELINE")

# Build forbidden pattern as a single ERE
PATTERN="$(forbidden_patterns | paste -sd'|' -)"

new_hits=(); seen_keys=(); scanned_repos=()
declare -A doors=()

# Fetch apps.conf and parse door mappings
if APPS_CONF="$(fetch_apps_conf)"; then
  while IFS='|' read -r domain repo; do
    doors["$domain"]="$repo"
  done < <(echo "$APPS_CONF" | parse_apps_conf_doors)
fi

# Scan via GitHub API (default) or local checkouts (USE_LOCAL=1)
if [ "$USE_LOCAL" = "1" ]; then
  DEV_ROOT="${DEV_ROOT:-$HOME/dev}"
  for gitdir in "$DEV_ROOT"/*/.git; do
    [ -d "$gitdir" ] || continue
    repo_dir="${gitdir%/.git}"
    repo="$(basename "$repo_dir")"
    ref="$(repo_ref "$repo_dir")"
    scanned_repos+=("$repo")

    while IFS= read -r line; do
      [ -n "$line" ] || continue
      path="${line%%:*}"
      rest="${line#*:}"
      is_exempt_path "$path" && continue
      is_public_doc "$path" || continue
      key="$repo/$path"
      seen_keys+=("$key")
      in_baseline "$key" "${KEYS[@]:-}" || new_hits+=("$key:$rest")
    done < <(git -C "$repo_dir" grep -nEI "$PATTERN" "$ref" -- '*.md' '*.html' 2>/dev/null | sed "s|^$ref:||" || true)

    # Check for door disagreements in READMEs
    if [ ${#doors[@]} -gt 0 ]; then
      while IFS= read -r line; do
        [ -n "$line" ] || continue
        path="${line%%:*}"
        rest="${line#*:}"
        case "$path" in *README.md|*readme.md) ;; *) continue ;; esac
        
        for domain in "${!doors[@]}"; do
          if echo "$rest" | grep -qF "$domain"; then
            expected_repo="${doors[$domain]}"
            if [ "$repo" != "$expected_repo" ]; then
              key="$repo/$path"
              detail="claims door $domain (apps.conf says $expected_repo)"
              seen_keys+=("$key")
              in_baseline "$key" "${KEYS[@]:-}" || new_hits+=("$key:$detail")
            fi
          fi
        done
      done < <(git -C "$repo_dir" grep -nEI '\.(orangecat\.ch|[a-z-]+\.(com|ch|org))' "$ref" -- '*README.md' '*readme.md' 2>/dev/null | sed "s|^$ref:||" || true)
    fi
  done
else
  # GitHub API scan (default)
  if ! command -v gh >/dev/null 2>&1; then
    echo "✗ gh CLI not found. Install it or set USE_LOCAL=1 to scan $HOME/dev" >&2
    exit 2
  fi

  mapfile -t repos < <(gh_list_repos)
  for repo in "${repos[@]}"; do
    [ -n "$repo" ] || continue
    scanned_repos+=("$repo")
    branch="$(gh_default_branch "$repo")"
    
    # Check root-level public docs
    for file in README.md CLAUDE.md AGENTS.md; do
      content="$(gh_check_file "$repo" "$file" "$branch")"
      [ -n "$content" ] || continue
      
      path="$file"
      is_exempt_path "$path" && continue
      
      # Check forbidden patterns
      if matches="$(echo "$content" | grep -oEI "$PATTERN" | head -1)"; then
        [ -n "$matches" ] || continue
        key="$repo/$path"
        detail="$matches"
        seen_keys+=("$key")
        in_baseline "$key" "${KEYS[@]:-}" || new_hits+=("$key:$detail")
      fi
      
      # Check for door disagreements in READMEs
      if [ ${#doors[@]} -gt 0 ] && [ "$file" = "README.md" ]; then
        for domain in "${!doors[@]}"; do
          if echo "$content" | grep -qF "$domain"; then
            expected_repo="${doors[$domain]}"
            if [ "$repo" != "$expected_repo" ]; then
              key="$repo/$path"
              detail="claims door $domain (apps.conf says $expected_repo)"
              seen_keys+=("$key")
              in_baseline "$key" "${KEYS[@]:-}" || new_hits+=("$key:$detail")
            fi
          fi
        done
      fi
    done
  done
fi

# Generate inventory
{
  echo "# org-drift inventory — GENERATED by org-drift-audit.sh"
  echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "#"
  echo "# Scanned ${#scanned_repos[@]} repos, found ${#seen_keys[@]} violation(s)"
  echo ""
  if [ ${#seen_keys[@]} -gt 0 ]; then
    printf '%s\n' "${seen_keys[@]}" | sort -u
  else
    echo "# No violations found"
  fi
} > "$INVENTORY"

# A runner that scans nothing passes vacuously
if [ ${#scanned_repos[@]} -eq 0 ]; then
  if [ "$USE_LOCAL" = "1" ]; then
    echo "⊘ org-drift audit SKIPPED — no fleet checkout under ${DEV_ROOT:-$HOME/dev}."
  else
    echo "⊘ org-drift audit SKIPPED — gh repo list returned nothing."
  fi
  echo "  This is not a pass. A ratchet that scans nothing prevents nothing."
  exit 0
fi

if [ "$MODE" = list ]; then
  printf '%s\n' "${seen_keys[@]:-}" | sort -u
  exit 0
fi

# Check baseline rise
stale=()
for k in "${KEYS[@]:-}"; do
  [ -n "$k" ] || continue
  repo="${k%%/*}"
  # Only check for stale entries if we actually scanned that repo
  scanned=0
  for r in "${scanned_repos[@]}"; do
    [ "$r" = "$repo" ] && { scanned=1; break; }
  done
  [ "$scanned" -eq 0 ] && continue
  in_baseline "$k" "${seen_keys[@]:-}" || stale+=("$k")
done

if [ ${#new_hits[@]} -gt 0 ]; then
  echo "✗ org-drift violations not in the baseline:" >&2
  printf '  %s\n' "${new_hits[@]}" >&2
  echo >&2
  echo "  These public documents contradict registers/org.json. Fix the claim," >&2
  echo "  or if this is a historical record, add the 'repo/path' line to" >&2
  echo "  $(basename "$BASELINE") WITH A REASON, in the same PR." >&2
  exit 1
fi

if [ ${#stale[@]} -gt 0 ]; then
  echo "✓ baseline entries with no matching violation — the ratchet fell:" >&2
  printf '  %s\n' "${stale[@]}" >&2
  echo "  Delete these lines from $(basename "$BASELINE")." >&2
  exit 1
fi

echo "✓ ${#scanned_repos[@]} repos swept, ${#seen_keys[@]} known violation(s), no new contradictions"
